### ISSUE TITLE
Unique naming convention for the atoms within lipids

### ISSUE THREAD

**Issue by ohsOllila** [NMRLipids/NMRlipidsIVPEandPG#19]
To speed up the analysis of the trajectories in the NMRlipids IVb project, we will build a beta version of NMRlipids databank containing the trajectories related to this project. For this, and for the future, we need to decide how to uniquely name the atoms within lipids in different force fields to enable automatic analysis of the data in the databank. Beta version of the [databank reader code is here](https://github.com/NMRLipids/NMRlipidsIVPEandPG/blob/master/scripts/readData.ipynb) and the [databank itself is here](https://github.com/NMRLipids/NMRlipidsIVPEandPG/tree/master/Data/Simulations).

Current plan is to use the [mapping file convention](http://nmrlipids.blogspot.com/2015/03/mapping-scheme-for-lipid-atom-names-for.html) extended to a three column format where the third column gives the "residue" name for each atom. Different mapping files will be available in the repository ([currently here](https://github.com/NMRLipids/NMRlipidsIVPEandPG/tree/master/scripts/mapping_files)). If suitable mapping files for a simulation are not available at the time of upload, the contributor has to create them. There is a [tool available](https://github.com/patrickfuchs/autoLipMap) by @patrickfuchs that helps in this, but some manual checking is still required (hopefully fully automatic in the future).

Any comments on this are welcomed. Especially opinions on alternative options for unique indexing of atoms names in different force fields.

**Comment by patrickfuchs** [comment]
Hi @ohsOllila, the plan sounds good. This extra column should solve the problem of spreading the atoms from one lipid to multiple residues.
To me your mapping file convention is suitable for the db project, each name is sufficiently general and easy to extend to any lipid with linear chains (maybe more difficult with lipids containing cycles such as sterols or inois, but I guess we won't look at those).
But just to be sure to make the right choice, you mentionned about "Sundaralingam notation" in your presentation. Do you have a ref for that? Regarding SMIRKS, this is very nice and general, but I'm not sure we need this level of complexity for collecting the order parameter of lipids from different FF. Unless there are future plans to go towards lipid FF parameterization?

**Comment by ohsOllila** [comment]
The Sundaralingam notation can be found from here: https://doi.org/10.1111/j.1749-6632.1972.tb54814.x

**Comment by ohsOllila** [comment]
The databank is moved to its own repository (https://github.com/NMRLipids/Databank) and mapping files will be used for now. Therefore, I close this issue.
