### ISSUE TITLE
File format and name of dictionary file

### ISSUE THREAD

**Issue by ohsOllila** [NMRLipids/NMRlipidsIVPEandPG#20]
At the first stage we saved the dictionary in json files. However, during the online discussion @hseara pointed out that yaml file format would be better. If this is practically feasible, we consider changing to this.

In this case, the dictionary files in the databank would be named README.yaml. Should we continue using this name, or are there some reasons to change the name?

Any comments on these issues are welcomed.

**Comment by batukav** [comment]
Hello @ohsOllila and @akiirik. 

I have some simulations coming and would like to use the AddData notebooks for processing the trajectories. Just for my information and maybe for the other that might be interested, what is the current workflow for using those notebooks?

**Comment by ohsOllila** [comment]
Hello @batukav,

the current version is here: https://github.com/NMRLipids/NMRlipidsIVPEandPG/blob/master/scripts/AddData.ipynb

You need to modify only the first cell until lipid names, which have to match with the ones in your simulation. In @MAPPING line, the molecule name and the name of mapping file are given. The mapping file has to be found from this directory:  https://github.com/NMRLipids/NMRlipidsIVPEandPG/tree/master/scripts/mapping_files in your local branch.
The databank is currently written in here: https://github.com/NMRLipids/NMRlipidsIVPEandPG/tree/master/Data/Simulations and this script contains examples of analysis and plotting: https://github.com/NMRLipids/NMRlipidsIVPEandPG/blob/master/scripts/plotDATA.ipynb

We are still working on this and will add at least the information about the time to be analyzed in the dictionary. Let us know if you try this and if you have any comments.

**Comment by batukav** [comment]
Hi @ohsOllila,

Thanks. In the current version of the AddData.ipynb we don't have the dictionary files required for the OpenMM. For the polarizable models project (https://github.com/NMRLipids/NMRlipidsVIpolarizableFFs) we need the OpenMM dictionaries added to the AddData.ipynb. I've done this on the polarizable models branch (https://github.com/NMRLipids/NMRlipidsVIpolarizableFFs/blob/master/AddData.ipynb). You might want to copy that change to the current version.

Regarding the analysis time, I think this would be a very good option to include. Currently, at least printing which frames are being analyzed to the OrderParameter.py could be quite useful.

**Comment by ohsOllila** [comment]
We are now using yaml files in the databank and they work fine, so I will close this.
