### ISSUE TITLE
Missing gro or tpr file

### ISSUE THREAD

**Issue by ohsOllila** [NMRLipids/NMRlipidsIVPEandPG#3]
I would like to have gro and/or tpr file for this entry https://github.com/NMRLipids/MATCH/tree/master/Data/Lipid_Bilayers/POPG%2B150mNaCl/T310K/MODEL_GROMOS-CKP, which probably comes from here https://doi.org/10.5281/zenodo.2572896. This would make it much easier for me to figure out which order parameter belongs to which carbon.

**Comment by peonqan** [comment]
I added the gro and tpr file to https://zenodo.org/record/3257649#.XROjHyZ7nLB

**Comment by ohsOllila** [comment]
Thanks, I have now added the data into the plot https://github.com/NMRLipids/NMRlipidsIVPEandPG/blob/master/Figs/HGorderparametersPG.pdf in this commit https://github.com/NMRLipids/NMRlipidsIVPEandPG/commit/13f5a9fc46055be69deaa612102d109adf3ee48b
