### ISSUE TITLE
Title for the NMRlipids IVb article

### ISSUE THREAD

**Issue by ohsOllila** [NMRLipids/NMRlipidsIVPEandPG#39]
We need to figure out a good title for the article. Current title is only the working title. Suggestions are welcomed here.

**Comment by markussmiettinen** [comment]
Protein–lipid interactions are not regulated by conformational restrictions of the phosphatidylcholine, -ethanolamine, -serine, and -glycerol headgroups

**Comment by ivan-gushchin-mipt** [comment]
I haven't participated in the earlier discussions, so my suggestion may be off. Overall, the work is similar to the previous one, so why not _"Headgroup structure and cation binding in phosphoethanolamine and phosphoglycerol lipid bilayers in simulations and experiments: critical comparison"_? Some words can be omitted, for example if the comparison is not critical. Or, the words can be shuffled. I guess there is not much that can be added or removed from the title.

Other similar ideas:
- Headgroup structure and cation binding in phosphoethanolamine and phosphoglycerol lipid bilayers in simulations and experiments: comparison with other lipid types - _too long?_
- Phospholipid headgroup structure and cation binding in simulations and experiments: critical comparison
- Headgroup structure and cation binding in PC, PE, PG and PS lipid bilayers in simulations and experiments: critical comparison - _usually, the editors are not happy with abbreviations in the titles_

**Comment by ivan-gushchin-mipt** [comment]
I really should've read the manuscript before suggesting the title. Having done that, I may also suggest:
- Conformational plasticity of phospholipid headgroups in simulations and experiment(s)
- Flexibility of phospholipid headgroups in simulations and experiment(s)
- Phospholipid headgroups in simulations and experiments: conformational plasticity and cation binding

**Comment by ohsOllila** [comment]
I like this one: "Conformational plasticity of phospholipid headgroups in simulations and experiments"

**Comment by markussmiettinen** [comment]
I like the concept _conformational plasticity_! But I think _simulations and experiments_ does not add much to the title. Thus I propose:

- Conformational plasticity of phospholipid headgroups
(Simpler, shorter, more general.)
- Conformational plasticity of phospholipid headgroups revealed by combining molecular dynamics simulations and solid-state NMR experiments
(Highlights our unique method.)

**Comment by tfmFerreira** [comment]
I agree with Markus that "simulations and experiments" is a bit too vague. I would suggest "Conformational plasticity of lipid headgroups in cellular membranes and protein-lipid complexes" but I also like the second option from Markus "Conformational plasticity of phospholipid headgroups revealed by combining molecular dynamics simulations and solid-state NMR experiments"

**Comment by ohsOllila** [comment]
This is my favorite:  "Conformational plasticity of lipid headgroups in cellular membranes and protein-lipid complexes"

**Comment by ivan-gushchin-mipt** [comment]
I agree with Markus and everybody, it is better to add details. All proposed variants look great to me.

**Comment by ohsOllila** [comment]
After comments from the editors, the title of the manuscript is now "Inverse conformational selection in lipid-protein binding". I will close this issue.
