### ISSUE TITLE
Improving TOC graphics

### ISSUE THREAD

**Issue by ohsOllila** [NMRLipids/NMRlipidsIVPEandPG#49]
Current TOC graphics looks like this:

![image](https://user-images.githubusercontent.com/7114769/124639808-44c22680-de95-11eb-85ed-6dc96522d5b6.png)

I think that there is room for improvement for the next submission. Let me know if you have any suggestions.

**Comment by jmelcr** [comment]
I had an idea on how to simplify the graphic, which I quickly sketched as the following

![2021-07 TOC graphic NMRlipids JACS](https://user-images.githubusercontent.com/12782348/124725227-ffd9d680-df0c-11eb-807a-26fda0119aed.png)

The flexible conformations of lipids are represented as the wobbly structures in the bilayer with cartoon-styled motion.

The *inverse conformational selection of proteins* is represented as previously by a super-well fitting cavity for the headgroup in the selected position without much freedom to move. 

We may add a few words, e.g. *"flexible configurations"* at the place of free lipids, 
and *"protein-selected configuration"* at the place of lipids bound to a protein,
but I would not put much more, as there will be a whole paragraph of text by the side of the figure explaining it in detail. 

The drawing was done in a non-vector editor Krita (freely available),
[and here is the Krita source file for download.](https://www.dropbox.com/s/ps7e2tybixkis1h/2021-07%20TOC%20graphic%20NMRlipids%20JACS.kra?dl=0)

**Comment by Regafandi** [comment]
Hi, with respect to the TOC, we could prepare a similar picture to that proposed by Josef Melcr but in a 3D-style (i.e. Blender). Would you like us to try something like this, or do you prefer the non-vector fashion?

**Comment by markussmiettinen** [comment]
In my opinion it would be best to keep the figure as simple as possible, that is, remain close to Samuli's original suggestion.

I think it is especially important to make the point that the SAME lipid can adapt to whatever binding pocket happens to be available for it. Therefore, I think it is important that each lipid is shown in its own box, not all together in one bilayer.

I also think it is important that the tails are in identical conformation for all the lipids, so the viewer will understand that the point is made about the headgroups, NOT the tails.

I would therefore suggest this modification of Samuli's original idea:

![TOC_NMRlipidsIVb 001](https://user-images.githubusercontent.com/5721866/125176985-8d048000-e1d8-11eb-8d88-2d17aa824012.png)

**Comment by ohsOllila** [comment]
Thank you for your suggestions.

The main question now is to select between visually appealing image and a schematic that aims to present our idea more accurately. I think that figure by @jmelcr makes already pretty good job being visually appealing. However, in this case I would prefer a figure which is explicitly aiming to demonstrate our idea even if that would compromise the visual appearance. Therefore, I would rather go to the direction suggested by @markussmiettinen.

However, the current version would be probably too high for the TOC figure requirements. Also, it might give an impression that there would exist proteins for which all lipids would bound in same conformation, and there are only peripheral proteins in the figure. Maybe removing third row, and putting four or three different proteins of which one is transmembrane on second row would work?

**Comment by markussmiettinen** [comment]
> it might give an impression that there would exist proteins for which all lipids would bound in same conformation

Indeed. In its current form the figure suggests that any lipid headgroup can adapt to the shape of the binding pocket in the protein. Avoiding this implication is challenging with this level of simplification. 

> Maybe removing third row, and putting four or three different proteins of which one is transmembrane on second row would work?

I think one row can only have one type of protein. Otherwise the table format will not work.

We could switch to have the different lipid types on the rows, and then 4-5 different protein columns. This would allow us to increase the width/height ratio to the value desired by JACS. In relation to this: Can we drop the naming of lipids as PC, PE, PG, and PS? Could they be just lipid headgroup 1, lipid headgroup 2, and lipid headgroup 3?

**Comment by markussmiettinen** [comment]
Here the tuned version:

![TOC_NMRlipidsIVb](https://user-images.githubusercontent.com/5721866/125272586-4d3eb500-e30c-11eb-8602-ff8a3a9c440b.png)

**Comment by ohsOllila** [comment]
Thanks. I will now submit the revised manuscript with this updated figure.

**Comment by ohsOllila** [comment]
The manuscript is now published, I will close this.
